# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Member": "00_typing.ipynb",
         "Mem": "00_typing.ipynb",
         "FunctionalEnum": "01_enum.ipynb",
         "DocumentedEnum": "01_enum.ipynb",
         "assign_annotations": "02_enumify.ipynb",
         "enumify": "02_enumify.ipynb"}

modules = ["typing.py",
           "enum.py",
           "enumify.py"]

doc_url = "https://muellerzr.github.io/enumify/"

git_url = "https://github.com/muellerzr/enumify/tree/main/"

def custom_doc_links(name): return None
