# AUTOGENERATED! DO NOT EDIT! File to edit: 00_typing.ipynb (unless otherwise specified).

__all__ = ['Member', 'Mem']

# Cell
class Member:
    """Annotation-only type, should be used with `@enumify` decorator

    Used to denote when a member will be of type `str`,
    with the value being its member name in lowercase.
    """
    def __init__(self, *args):
        raise TypeError("Member is a documentation type, cannot be instantiated")

Mem = Member